description: |-
  This playbook will be executed from the “Proactive Threat Hunting” layout button with the objective of quarantine a file specified by the analyst. The following integrations is supported:
  - Cortex XDR IR
id: Proactive Threat Hunting - Quarantine File
inputs: []
name: Proactive Threat Hunting - Quarantine File
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 35c489f4-3d7c-4d13-882c-4bbc8fd7c5a1
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 35c489f4-3d7c-4d13-882c-4bbc8fd7c5a1
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "2":
    continueonerrortype: ""
    fieldMapping:
    - incidentfield: User Block Status
      output:
        simple: Executed
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: true
    quietmode: 0
    scriptarguments:
      value:
        simple: Quarantine file procedure has executed. Follow the work plan to continue.
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 7e850afe-3652-4e16-8e64-76d27b1e5381
      iscommand: false
      name: Print update to notes
      script: Print
      type: regular
      version: -1
    taskid: 7e850afe-3652-4e16-8e64-76d27b1e5381
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 180
        }
      }
  "3":
    continueonerrortype: ""
    form:
      description: ""
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: Provide endpoint ID
        options: []
        optionsarg:
        - {}
        - complex:
            accessor: affectedusers
            root: incident
        placeholder: ""
        readonly: false
        required: false
        tooltip: ""
        type: shortText
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "1"
        label: ""
        labelarg:
          simple: Provide file path
        options: []
        optionsarg: []
        placeholder: ""
        readonly: false
        required: false
        tooltip: ""
        type: shortText
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "2"
        label: ""
        labelarg:
          simple: Provide file hash
        options: []
        optionsarg: []
        placeholder: ""
        readonly: false
        required: false
        tooltip: ""
        type: shortText
      sender: ""
      title: Provide details for file quarantine
      totalanswers: 0
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc:
      body:
      cc:
      format: ""
      methods: []
      subject:
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: true
        retriescount: 2
        retriesinterval: 360
      to:
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: ''
      id: 1c73dc0d-8a10-46b1-8261-5c3d1456ffef
      iscommand: false
      name: Provide details for file quarantine
      type: collection
      version: -1
    taskid: 1c73dc0d-8a10-46b1-8261-5c3d1456ffef
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 450,
          "y": 340
        }
      }
  "4":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: "0"
                root: Provide details for file quarantine.Answers
          operator: isNotEmpty
          right:
            value: {}
      - - left:
            iscontext: true
            value:
              complex:
                accessor: "1"
                root: Provide details for file quarantine.Questions
          operator: isNotEmpty
      - - left:
            iscontext: true
            value:
              complex:
                accessor: "2"
                root: Provide details for file quarantine.Answers
          operator: isNotEmpty
      label: "yes"
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: ''
      id: 7e70a140-5c50-439e-80de-e80725223c92
      iscommand: false
      name: Has file to quarantine?
      type: condition
      version: -1
    taskid: 7e70a140-5c50-439e-80de-e80725223c92
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 500
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e171a237-98a4-4a7f-8a18-4ced40b8491d
      iscommand: false
      name: Done
      type: title
      version: -1
      description: ''
    taskid: e171a237-98a4-4a7f-8a18-4ced40b8491d
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 840
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      endpoint_id_list:
        complex:
          accessor: "0"
          root: Provide details for file quarantine.Questions
      file_hash:
        complex:
          accessor: "2"
          root: Provide details for file quarantine.Answers
      file_path:
        complex:
          accessor: "1"
          root: Provide details for file quarantine.Answers
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Quarantines a file on selected endpoints. You can select up to 1000 endpoints.
      id: 3d38dd61-7381-44d2-82b5-3d880f9cc271
      iscommand: true
      name: Quarantine file
      script: '|||xdr-file-quarantine'
      type: regular
      version: -1
    taskid: 3d38dd61-7381-44d2-82b5-3d880f9cc271
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 890,
          "y": 670
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "4_5_#default#": 0.55
    },
    "paper": {
      "dimensions": {
        "height": 855,
        "width": 820,
        "x": 450,
        "y": 50
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.9.0
