contentitemexportablefields:
  contentitemfields: {}
id: 'CTF 3 - Cortex XDR - Image spooned a suspicious activity'
inputs: []
name: 'CTF 3 - Cortex XDR - Image spooned a suspicious activity'
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "19"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 55f2d7f4-a8b2-457e-8bf4-e9256de21a0e
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 55f2d7f4-a8b2-457e-8bf4-e9256de21a0e
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 220
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      CVE:
        complex:
          accessor: ID
          root: CVE
      Domain:
        complex:
          accessor: Name
          root: Domain
          transformers:
          - operator: uniq
      Email:
        complex:
          accessor: Email.Address
          root: Account
          transformers:
          - operator: uniq
      Hostname:
        complex:
          accessor: Hostname
          root: Endpoint
          transformers:
          - operator: uniq
      IP:
        complex:
          accessor: Address
          root: IP
          transformers:
          - operator: uniq
      MD5:
        complex:
          accessor: MD5
          root: File
          transformers:
          - operator: uniq
      ResolveIP:
        simple: "False"
      SHA1:
        complex:
          accessor: SHA1
          root: File
          transformers:
          - operator: uniq
      SHA256:
        complex:
          accessor: SHA256
          root: File
          transformers:
          - operator: uniq
      URL:
        complex:
          accessor: Data
          root: URL
          transformers:
          - operator: uniq
      Username:
        complex:
          accessor: Username
          root: Account
          transformers:
          - operator: uniq
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: Enrich entities using one or more integrations.
      id: 1f94564f-9374-4d34-8fb5-141f24d2e4e3
      iscommand: false
      name: Entity Enrichment - Generic v3
      playbookId: Entity Enrichment - Generic v3
      type: playbook
      version: -1
    taskid: 1f94564f-9374-4d34-8fb5-141f24d2e4e3
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 265,
          "y": 660
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 64f89a11-fc58-4d2b-89de-ffa7e67df36e
      iscommand: false
      name: Enrichmnet
      type: title
      version: -1
      description: ''
    taskid: 64f89a11-fc58-4d2b-89de-ffa7e67df36e
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 265,
          "y": 515
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a2968bbd-05e9-46f3-85ac-539bf5fa8f0f
      iscommand: false
      name: 'Calculate Severity '
      type: title
      version: -1
      description: ''
    taskid: a2968bbd-05e9-46f3-85ac-539bf5fa8f0f
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 265,
          "y": 835
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    scriptarguments:
      Account:
        complex:
          root: Account
          transformers:
          - operator: uniq
      CriticalEndpoints:
        simple: admin
      CriticalGroups:
        simple: admins,administrators
      CriticalUsers:
        simple: admin,administrator
      DBotScore:
        complex:
          root: DBotScore
      EmailAuthenticityCheck:
        complex:
          accessor: AuthenticityCheck
          root: Email
          transformers:
          - operator: uniq
      Endpoint:
        complex:
          root: Endpoint
          transformers:
          - operator: uniq
      MicrosoftHeadersSeverityCheck:
        simple: ${Email.MicrosoftHeadersSeverityCheck}
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Calculate and assign the incident severity based on the highest returned severity level from the following calculations:

        - DBotScores of indicators
        - Critical assets
        - Email authenticity
        - Current incident severity
        - Microsoft Headers
      id: 6634b11d-6a16-422a-834d-1995e4097958
      iscommand: false
      name: Calculate Severity - Generic v2
      playbookId: Calculate Severity - Generic v2
      type: playbook
      version: -1
    taskid: 6634b11d-6a16-422a-834d-1995e4097958
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 265,
          "y": 980
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "11"
      - "17"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e72c7841-588e-4bf8-8ea3-457462b666fa
      iscommand: false
      name: 'Investigation '
      type: title
      version: -1
      description: ''
    taskid: e72c7841-588e-4bf8-8ea3-457462b666fa
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1155
        }
      }
  "11":
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      FileSha256:
        simple: ${incident.filesha256}
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: 'This playbook searches for a specific hash in the supported sandboxes. If the hash is known, the playbook provides a detailed analysis of the sandbox report. Currently, supported sandboxes are Falcon Intelligence Sandbox, Wildfire and Joe Sandbox. '
      id: d51d1ca8-8cec-4df2-8169-b242c959dcf3
      iscommand: false
      name: Search For Hash In Sandbox - Generic
      playbookId: Search For Hash In Sandbox - Generic
      type: playbook
      version: -1
    taskid: d51d1ca8-8cec-4df2-8169-b242c959dcf3
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1650
        }
      }
  "12":
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: "Seems like SecOps did it again? It seems someone forgot to add all the required items for us to go and check the image… Maybe running Optical Character Recognition (OCR) can help us here?\n\n I remember we had an automation started with !image-ocr-ex.... for such scenario :wink: "
      id: fffa1f2a-559c-4ae9-8ce2-ad5aaf5c5914
      iscommand: false
      name: Oh, Snap!!! - Where are all the other tasks that we need?
      type: regular
      version: -1
    taskid: fffa1f2a-559c-4ae9-8ce2-ad5aaf5c5914
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 250,
          "y": 2070
        }
      }
  "13":
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "14"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: "Message from the outside...\n\n\nᗪ闩爪爪 ㄒ廾闩ㄒ 山闩丂 千闩丂ㄒ... 廾龱尸㠪 ㄒ廾闩ㄒ ㄚ龱ㄩ 工\U0001D4DDᐯ㠪丂ㄒ工Ꮆ闩ㄒ㠪ᗪ ㄒ廾㠪 工\U0001D4DDᗪ工⼕闩ㄒ龱尺. \n爪闩ㄚ乃㠪 ㄒ廾㠪尺㠪 闩尺㠪 龱ㄒ廾㠪尺 工\U0001D4DD⼕工ᗪ㠪\U0001D4DDㄒ丂 山工ㄒ廾 ㄒ廾工丂 工\U0001D4DDᗪ工⼕闩ㄒ龱尺?\n\n\n![my_file](https://raw.githubusercontent.com/demisto/content/7c4eb1780678929fac94695180de3537c0f56f23/Packs/ctf01/doc_files/yoda-8ball.gif)"
      id: 13b79616-e678-4c83-86f2-a8b2296213fc
      iscommand: false
      name: R u Sure?
      type: regular
      version: -1
    taskid: 13b79616-e678-4c83-86f2-a8b2296213fc
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 250,
          "y": 2245
        }
      }
  "14":
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: In order to answer this you will need to run the CTF_3 automation/script with the provided answer
      id: d8abe179-60e4-4f0e-8c8c-517847d83785
      iscommand: false
      name: Soooooo who is the person behind this attack?
      type: regular
      version: -1
    taskid: d8abe179-60e4-4f0e-8c8c-517847d83785
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 250,
          "y": 2420
        }
      }
  "15":
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 22007ab8-216b-4412-803c-ccf30d7a058d
      iscommand: false
      name: Finalizing
      type: title
      version: -1
      description: ''
    taskid: 22007ab8-216b-4412-803c-ccf30d7a058d
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 250,
          "y": 1910
        }
      }
  "16":
    continueonerrortype: ""
    id: "16"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "18"
    note: false
    quietmode: 0
    scriptarguments:
      EntryID:
        simple: ${File.EntryID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Converts an image file to a PDF file.
      id: 299a7cf3-8125-4780-84b7-7e0d7146e405
      iscommand: true
      name: Rasterize Image -> PDF
      script: '|||rasterize-image'
      type: regular
      version: -1
    taskid: 299a7cf3-8125-4780-84b7-7e0d7146e405
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1470
        }
      }
  "17":
    continueonerrortype: ""
    id: "17"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Retrieves files from selected endpoints. You can retrieve up to 20 files, from no more than 10 endpoints. At least one endpoint ID and one file path are necessary in order to run the command. After running this command, you can use the xdr-action-status-get command with returned action_id, to check the action status.
      id: 1be10ab5-60cd-428f-80a6-6c4a91c64fbe
      iscommand: true
      name: Cortex XDR - Retrieve File
      script: '|||xdr-file-retrieve-ctf'
      type: regular
      version: -1
    taskid: 1be10ab5-60cd-428f-80a6-6c4a91c64fbe
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1300
        }
      }
  "18":
    continueonerrortype: ""
    id: "18"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      EntryID:
        complex:
          accessor: EntryID
          filters:
          - - ignorecase: true
              left:
                iscontext: true
                value:
                  simple: InfoFile.Extension
              operator: containsGeneral
              right:
                value:
                  simple: pdf
          root: InfoFile
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Converts a PDF file to an image file.
      id: 199f0920-51f9-43c1-8ff9-5b6463f3472f
      iscommand: true
      name: Rasterize PDF -> Image
      script: '|||rasterize-pdf'
      tags:
      - endpoint_image
      type: regular
      version: -1
    taskid: 199f0920-51f9-43c1-8ff9-5b6463f3472f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1650
        }
      }
  "19":
    continueonerrortype: ""
    id: "19"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: "Welcome to the Final CTF -> AKA CTF #3\n\nUse all the knowledge & tools that you have gained from the previous Capture the Flag exercises. \nIn this CTF, you will need to fix errors in the playbook to continue with the challenge.\n\nWhen you have the answer you can complete the CTF by running the automation ‘CTF_3’ in the incident. Then check the answer in the war room. \n\nNote that this CTF is a bit more difficult than the others, but don't give up so quickly -> it's easier than you think.\nWe believe that you can do this!\n\nWhen you are ready -> complete this task to proceed.\n\n![myfile](https://raw.githubusercontent.com/demisto/content/1c8915d79a2dd62593c8d0e7f1a303973e44bbe1/Packs/ctf01/doc_files/do-this.gif)"
      id: 633bd0fb-8eb4-4525-8af0-855bb1a55d1b
      iscommand: false
      name: 'Welcome to CTF #3'
      type: regular
      version: -1
    taskid: 633bd0fb-8eb4-4525-8af0-855bb1a55d1b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 350
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2295,
        "width": 810,
        "x": 50,
        "y": 220
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 6.8.0
description: 'CTF #3'
