commonfields:
  id: Proofpoint on Demand Email Security Event Collector
  version: -1
name: Proofpoint on Demand Email Security Event Collector
display: Proofpoint on Demand Email Security Event Collector
category: Analytics & SIEM
description: Collects events for Proofpoint using the streaming API.
configuration:
- display: Server Host
  name: host
  type: 0
  required: true
- displaypassword: API key
  name: api_key
  hiddenusername: true
  type: 9
  required: true
- display: XSIAM request limit
  name: limit
  type: 0
  defaultvalue: 1000
  required: true
- display: Request retries
  name: retries
  type: 0
  defaultvalue: 5
  required: false
- display: Use system proxy settings
  name: proxy
  type: 8
  required: false
script:
  script: ""
  type: python
  commands:
  - arguments:
    - auto: PREDEFINED
      defaultValue: 'False'
      description: Set this argument to True in order to create events, otherwise the command will only display them.
      name: should_push_events
      predefined:
      - 'True'
      - 'False'
      required: true
    description: Manual command to fetch events and display them.
    name: duo-get-events
  dockerimage: devdemisto/python3:3.10.12.69053
  longRunning: true
  subtype: python3
marketplaces:
- marketplacev2
fromversion: 6.8.0
tests:
- No tests
