id: Tenable.io test
version: -1
name: Tenable.io test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: c6c8a575-ac97-4c57-8985-0c8c2dbddf84
    type: start
    task:
      id: c6c8a575-ac97-4c57-8985-0c8c2dbddf84
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 02f8833a-276b-4b9e-831c-34e78e2f5ab4
    type: regular
    task:
      id: 02f8833a-276b-4b9e-831c-34e78e2f5ab4
      version: -1
      name: tenable-io-list-scans
      description: Retrive scans from the Tenable platform.
      script: '|||tenable-io-list-scans'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      retry-count:
        simple: "2"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 449437fd-8d0d-4dff-8ae2-14cd72c9fbcb
    type: regular
    task:
      id: 449437fd-8d0d-4dff-8ae2-14cd72c9fbcb
      version: -1
      name: tenable-io-get-scan-status
      description: 'Check the status of a specific scan using its ID. The status can
        hold following possible values : Running, Completed and Empty (Ready to run).'
      script: '|||tenable-io-get-scan-status'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      retry-count:
        simple: "2"
      scanId:
        simple: "16"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 9614d1d3-fb7c-4b3e-84df-66a37dbe8893
    type: regular
    task:
      id: 9614d1d3-fb7c-4b3e-84df-66a37dbe8893
      version: -1
      name: tenable-io-get-scan-report
      description: Retrive scan-report for the given scan.
      script: '|||tenable-io-get-scan-report'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      detailed:
        simple: "yes"
      info:
        simple: "yes"
      retry-count:
        simple: "2"
      scanId:
        simple: "16"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: c35c7a8d-cf71-44c3-867b-95973eae02f9
    type: regular
    task:
      id: c35c7a8d-cf71-44c3-867b-95973eae02f9
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 63b25736-4cf8-4558-8393-afa52547bf6f
    type: regular
    task:
      id: 63b25736-4cf8-4558-8393-afa52547bf6f
      version: -1
      name: tenable-io-get-vulnerability-details
      description: Retrieve details for the given vulnerability.
      script: '|||tenable-io-get-vulnerability-details'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      retry-count:
        simple: "2"
      vulnerabilityId:
        complex:
          root: TenableIO
          accessor: Vulnerabilities.[0].Id
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 8299cc5a-ed19-4d7a-88c3-9367b5f889f7
    type: regular
    task:
      id: 8299cc5a-ed19-4d7a-88c3-9367b5f889f7
      version: -1
      name: tenable-io-get-vulnerabilities-by-asset
      description: Get a list of up to 5000 of the vulnerabilities recorded for a
        given asset. By default, this list is sorted by vulnerability count, descending.
      script: '|||tenable-io-get-vulnerabilities-by-asset'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      hostname:
        simple: ec2-52-50-45-109.eu-west-1.compute.amazonaws.com
      retry-count:
        simple: "2"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: bbbfda0b-1553-4185-817b-d11b787fb8bd
    type: regular
    task:
      id: bbbfda0b-1553-4185-817b-d11b787fb8bd
      version: -1
      name: Tenable-io-export-assets
      description: Retrieves details for the specified asset to include custom attributes.
      script: '|||tenable-io-export-assets'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      chunkSize:
        simple: "500"
      serviceNowSysId:
        simple: "false"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: f5aca946-7998-4349-8406-af958323e879
    type: regular
    task:
      id: f5aca946-7998-4349-8406-af958323e879
      version: -1
      name: Tenable-io-export-vulnerability
      description: Retrieves details for the specified asset to include custom attributes.
      script: Tenable.io|||tenable-io-export-vulnerabilities
      type: regular
      iscommand: true
      brand: Tenable.io
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      numAssets:
        simple: "500"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: 5688eba5-b52a-49ea-85f4-9a4611f33454
    type: condition
    task:
      id: 5688eba5-b52a-49ea-85f4-9a4611f33454
      version: -1
      name: Verify vulnerabilities
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "12"
      - "13"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: TenableIO.Vulnerability.asset
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: f8b35fd8-eedd-4b54-8cf2-d62e01c0daa5
    type: condition
    task:
      id: f8b35fd8-eedd-4b54-8cf2-d62e01c0daa5
      version: -1
      name: Verify assets
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "8"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: TenableIO.Asset.id
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: 71e70fae-1bd1-430b-8e1e-6ae63ed3ad91
    type: title
    task:
      id: 71e70fae-1bd1-430b-8e1e-6ae63ed3ad91
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 2295
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: 53df8437-0b55-47ce-8cae-e6a8fb679000
    type: regular
    task:
      id: 53df8437-0b55-47ce-8cae-e6a8fb679000
      version: -1
      name: Run get-scan-history Command
      description: Lists the individual runs of the specified scan.
      script: Tenable.io|||tenable-io-get-scan-history
      type: regular
      iscommand: true
      brand: Tenable.io
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      excludeRollover:
        simple: "true"
      page:
        simple: "2"
      pageSize:
        simple: "1"
      scanId:
        simple: "16"
      sortFields:
        simple: end_date,status
      sortOrder:
        simple: desc
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1945
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "13":
    id: "13"
    taskid: d9871de6-59ae-4674-87a3-f1e466c23ca6
    type: regular
    task:
      id: d9871de6-59ae-4674-87a3-f1e466c23ca6
      version: -1
      name: Run list-scan-filters Command
      description: Lists the filtering, sorting, and pagination capabilities available
        for scan records on endpoints/commands that support them.
      script: Tenable.io|||tenable-io-list-scan-filters
      type: regular
      iscommand: true
      brand: Tenable.io
    nexttasks:
      '#none#':
      - "14"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1945
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "14":
    id: "14"
    taskid: cba667e0-e859-4813-891b-c7a829e6095a
    type: regular
    task:
      id: cba667e0-e859-4813-891b-c7a829e6095a
      version: -1
      name: Run export-scan Command
      description: Export and download a scan report.
      script: Tenable.io|||tenable-io-export-scan
      type: regular
      iscommand: true
      brand: Tenable.io
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      assetId:
        simple: "10"
      chapters:
        simple: vuln_hosts_summary,remediations,compliance_exec,vuln_by_host,compliance,vuln_by_plugin
      filterName:
        complex:
          root: TenableIO.ScanFilter.name
          transformers:
          - operator: slice
            args:
              from:
                value:
                  simple: "1"
              to:
                value:
                  simple: "3"
      filterQuality:
        complex:
          root: TenableIO.ScanFilter.operators
          transformers:
          - operator: slice
            args:
              from:
                value:
                  simple: "1"
              to:
                value:
                  simple: "3"
      filterSearchType:
        simple: or
      filterValue:
        complex:
          root: TenableIO.ScanFilter.control
          accessor: readable_regex
          transformers:
          - operator: slice
            args:
              from:
                value:
                  simple: "1"
              to:
                value:
                  simple: "3"
      format:
        simple: HTML
      historyId:
        simple: ${TenableIO.ScanHistory.id}
      historyUuid:
        simple: ${TenableIO.ScanHistory.scan_uuid}
      scanId:
        simple: "16"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 2120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2310,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: 5.0.0
description: ""
