id: Tenable.io Run And Export Scan Test
version: -1
name: Tenable.io Run And Export Scan Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 3e71dac7-f071-4cce-8fd8-ea8d45cfa36e
    type: start
    task:
      id: 3e71dac7-f071-4cce-8fd8-ea8d45cfa36e
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: f3496d83-f168-44f0-81b0-ed92c9daf7b7
    type: playbook
    task:
      id: f3496d83-f168-44f0-81b0-ed92c9daf7b7
      version: -1
      name: Tenable.io Scan
      playbookName: Tenable.io Scan
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
      - "3"
    scriptarguments:
      scan-id:
        simple: "16"
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 64853254-3f54-4a24-8195-0ae5c3a46ce8
    type: regular
    task:
      id: 64853254-3f54-4a24-8195-0ae5c3a46ce8
      version: -1
      name: Run get-scan-history Command
      description: Lists the individual runs of the specified scan.
      script: Tenable.io|||tenable-io-get-scan-history
      type: regular
      iscommand: true
      brand: Tenable.io
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      excludeRollover:
        simple: "true"
      page:
        simple: "2"
      pageSize:
        simple: "1"
      scanId:
        simple: "16"
      sortFields:
        simple: end_date,status
      sortOrder:
        simple: desc
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 2bfe5482-f813-4f98-8273-e8c18a00b9bb
    type: regular
    task:
      id: 2bfe5482-f813-4f98-8273-e8c18a00b9bb
      version: -1
      name: Run list-scan-filters Command
      description: Lists the filtering, sorting, and pagination capabilities available
        for scan records on endpoints/commands that support them.
      script: Tenable.io|||tenable-io-list-scan-filters
      type: regular
      iscommand: true
      brand: Tenable.io
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 3a5011bf-2735-4df0-880e-c238aae33516
    type: regular
    task:
      id: 3a5011bf-2735-4df0-880e-c238aae33516
      version: -1
      name: Run export-scan Command
      description: Export and download a scan report.
      script: Tenable.io|||tenable-io-export-scan
      type: regular
      iscommand: true
      brand: Tenable.io
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      assetId:
        simple: "10"
      chapters:
        simple: vuln_hosts_summary,remediations,compliance_exec,vuln_by_host,compliance,vuln_by_plugin
      filterName:
        complex:
          root: TenableIO.ScanFilter.name
          transformers:
          - operator: slice
            args:
              from:
                value:
                  simple: "1"
              to:
                value:
                  simple: "3"
      filterQuality:
        complex:
          root: TenableIO.ScanFilter.operators
          transformers:
          - operator: slice
            args:
              from:
                value:
                  simple: "1"
              to:
                value:
                  simple: "3"
      filterSearchType:
        simple: or
      filterValue:
        complex:
          root: TenableIO.ScanFilter.control
          accessor: regex
          transformers:
          - operator: slice
            args:
              from:
                value:
                  simple: "1"
              to:
                value:
                  simple: "3"
      format:
        simple: HTML
      historyId:
        simple: ${TenableIO.ScanHistory.id}
      historyUuid:
        simple: ${TenableIO.ScanHistory.scan_uuid}
      scanId:
        simple: "16"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 4679396d-12de-4f96-8d83-75b8cf3d89d0
    type: title
    task:
      id: 4679396d-12de-4f96-8d83-75b8cf3d89d0
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 735,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: 5.0.0
description: ''
