id: Tenable.io test
version: -1
name: Tenable.io test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 3eb1d5e6-bcb1-4a56-8c2d-64454ee75da4
    type: start
    task:
      id: 3eb1d5e6-bcb1-4a56-8c2d-64454ee75da4
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      "#none#":
        - "4"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: fc0ab069-67dc-4656-840e-40e061fa5975
    type: regular
    task:
      id: fc0ab069-67dc-4656-840e-40e061fa5975
      version: -1
      name: tenable-io-list-scans
      description: Retrive scans from the Tenable platform.
      script: "|||tenable-io-list-scans"
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      "#none#":
        - "2"
    scriptarguments:
      retry-count:
        simple: "2"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 17b6cd73-2dc3-45e7-85d5-ce88bd5fb133
    type: regular
    task:
      id: 17b6cd73-2dc3-45e7-85d5-ce88bd5fb133
      version: -1
      name: tenable-io-get-scan-status
      description:
        "Check the status of a specific scan using its ID. The status can
        hold following possible values : Running, Completed and Empty (Ready to run)."
      script: "|||tenable-io-get-scan-status"
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      "#none#":
        - "3"
    scriptarguments:
      retry-count:
        simple: "2"
      scanId:
        simple: "16"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 3426c644-a954-47ad-8c11-ae8ad0128a1a
    type: regular
    task:
      id: 3426c644-a954-47ad-8c11-ae8ad0128a1a
      version: -1
      name: tenable-io-get-scan-report
      description: Retrive scan-report for the given scan.
      script: "|||tenable-io-get-scan-report"
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      "#none#":
        - "6"
    scriptarguments:
      detailed:
        simple: "yes"
      info:
        simple: "yes"
      retry-count:
        simple: "2"
      scanId:
        simple: "16"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: c29ead08-0608-4606-8d8a-47502664aa06
    type: regular
    task:
      id: c29ead08-0608-4606-8d8a-47502664aa06
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      "#none#":
        - "1"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 032d62f2-48ee-4da9-8d44-102483d55381
    type: regular
    task:
      id: 032d62f2-48ee-4da9-8d44-102483d55381
      version: -1
      name: tenable-io-get-vulnerability-details
      description: Retrieve details for the given vulnerability.
      script: "|||tenable-io-get-vulnerability-details"
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      "#none#":
        - "7"
    scriptarguments:
      retry-count:
        simple: "2"
      vulnerabilityId:
        complex:
          root: TenableIO
          accessor: Vulnerabilities.[0].Id
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: d100973b-5dd5-42bc-81e1-9823410df2bd
    type: regular
    task:
      id: d100973b-5dd5-42bc-81e1-9823410df2bd
      version: -1
      name: tenable-io-get-vulnerabilities-by-asset
      description:
        Get a list of up to 5000 of the vulnerabilities recorded for a
        given asset. By default, this list is sorted by vulnerability count, descending.
      script: "|||tenable-io-get-vulnerabilities-by-asset"
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      "#none#":
        - "5"
    scriptarguments:
      hostname:
        simple: ec2-52-50-45-109.eu-west-1.compute.amazonaws.com
      retry-count:
        simple: "2"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: af2fd25a-6070-4fcb-8ac0-17f7600230c2
    type: regular
    task:
      id: af2fd25a-6070-4fcb-8ac0-17f7600230c2
      version: -1
      name: Tenable-io-export-assets
      description: Retrieves details for the specified asset to include custom attributes.
      script: "|||tenable-io-export-assets"
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      "#none#":
        - "10"
    scriptarguments:
      chunkSize:
        simple: "500"
      serviceNowSysId:
        simple: "false"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: 15d882e0-c3d6-4ff4-84a5-7b3204797396
    type: regular
    task:
      id: 15d882e0-c3d6-4ff4-84a5-7b3204797396
      version: -1
      name: Tenable-io-export-vulnerability
      description: Retrieves details for the specified asset to include custom attributes.
      script: Tenable.io|||tenable-io-export-vulnerabilities
      type: regular
      iscommand: true
      brand: Tenable.io
    nexttasks:
      "#none#":
        - "9"
    scriptarguments:
      numAssets:
        simple: "500"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: 8dc9bb01-ba06-4464-8cd2-4be0fe360fee
    type: condition
    task:
      id: 8dc9bb01-ba06-4464-8cd2-4be0fe360fee
      version: -1
      name: Verify vulnerabilities
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
        - "12"
    separatecontext: false
    conditions:
      - label: "yes"
        condition:
          - - operator: isNotEmpty
              left:
                value:
                  simple: TenableIO.Vulnerability.asset
                iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: afb82e34-3d4c-4307-84dc-f7e2f3f866b7
    type: condition
    task:
      id: afb82e34-3d4c-4307-84dc-f7e2f3f866b7
      version: -1
      name: Verify assets
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
        - "8"
    separatecontext: false
    conditions:
      - label: "yes"
        condition:
          - - operator: isNotEmpty
              left:
                value:
                  simple: TenableIO.Asset.id
                iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: 681e360e-2a88-441d-8141-87cfb3801e5f
    type: title
    task:
      id: 681e360e-2a88-441d-8141-87cfb3801e5f
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: 6095f68c-243e-490f-8729-16a5f268ce9c
    type: playbook
    task:
      id: 6095f68c-243e-490f-8729-16a5f268ce9c
      version: -1
      name: Tenable.io Run And Export Scan Test
      playbookName: Tenable.io Run And Export Scan Test
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      "#none#":
        - "11"
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1945
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2135,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: 5.0.0
description: ""
