id: Tenable.io Scan Test
version: -1
name: Tenable.io Scan Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: cce5c0b6-d002-46e7-8ec6-ec50bc150e19
    type: start
    task:
      id: cce5c0b6-d002-46e7-8ec6-ec50bc150e19
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 663f0dbb-894b-4073-87ff-a5e77c43a162
    type: regular
    task:
      id: 663f0dbb-894b-4073-87ff-a5e77c43a162
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: facabc59-d0bb-464f-8745-62ffcac89667
    type: playbook
    task:
      id: facabc59-d0bb-464f-8745-62ffcac89667
      version: -1
      name: Tenable.io Scan
      description: Run a Tenable.io scan
      playbookName: Tenable.io Scan
      type: playbook
      iscommand: false
      brand: ""
    scriptarguments:
      scan-id:
        complex:
          root: TenableIO.Scan
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: TenableIO.Scan.Status
                iscontext: true
              right:
                value:
                  simple: completed
          accessor: Id
          transformers:
          - operator: atIndex
            args:
              index:
                value:
                  simple: "0"
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 49ba907d-1814-40b1-8d34-c27a4f488de1
    type: playbook
    task:
      id: 49ba907d-1814-40b1-8d34-c27a4f488de1
      version: -1
      name: GenericPolling
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      playbookName: GenericPolling
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      Ids:
        complex:
          root: TenableIO.Scan
          accessor: Id
          transformers:
          - operator: atIndex
            args:
              index:
                value:
                  simple: "0"
      Interval:
        simple: "1"
      PollingCommandArgName:
        simple: scanId
      PollingCommandName:
        simple: tenable-io-get-scan-status
      Timeout:
        simple: "10"
      dt:
        simple: |
          TenableIO.Scan(val.Status == 'pending' || val.Status == 'running' || val.Status == 'publishing').Id
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 733425c5-96e1-4ddb-8cc1-f43fe6de828e
    type: regular
    task:
      id: 733425c5-96e1-4ddb-8cc1-f43fe6de828e
      version: -1
      name: 'tenable.io list scans '
      description: Retrieves scans from the Tenable platform.
      script: '|||tenable-io-list-scans'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 765,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: 5.0.0
description: ''
