id: Tenable.io test
version: -1
name: Tenable.io test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: f719c97e-827c-4b3a-8d90-15d4d944de7f
    type: start
    task:
      id: f719c97e-827c-4b3a-8d90-15d4d944de7f
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: b4be35a2-c6c2-43f0-80df-cf78f23b2921
    type: regular
    task:
      id: b4be35a2-c6c2-43f0-80df-cf78f23b2921
      version: -1
      name: tenable-io-list-scans
      description: Retrive scans from the Tenable platform.
      script: '|||tenable-io-list-scans'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      retry-count:
        simple: "2"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: b823f1ef-0065-4698-882a-f888eac8b9aa
    type: regular
    task:
      id: b823f1ef-0065-4698-882a-f888eac8b9aa
      version: -1
      name: tenable-io-get-scan-status
      description: 'Check the status of a specific scan using its ID. The status can
        hold following possible values : Running, Completed and Empty (Ready to run).'
      script: '|||tenable-io-get-scan-status'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      retry-count:
        simple: "2"
      scanId:
        simple: "16"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 25d1d634-916b-49a4-85b1-f78ed2aa9f90
    type: regular
    task:
      id: 25d1d634-916b-49a4-85b1-f78ed2aa9f90
      version: -1
      name: tenable-io-get-scan-report
      description: Retrive scan-report for the given scan.
      script: '|||tenable-io-get-scan-report'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      detailed:
        simple: "yes"
      info:
        simple: "yes"
      retry-count:
        simple: "2"
      scanId:
        simple: "16"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 207d061b-ea1f-4c0e-8d49-de23521a1e8e
    type: regular
    task:
      id: 207d061b-ea1f-4c0e-8d49-de23521a1e8e
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 31fc1025-789c-4d47-811b-1b9ff3b6dc23
    type: regular
    task:
      id: 31fc1025-789c-4d47-811b-1b9ff3b6dc23
      version: -1
      name: tenable-io-get-vulnerability-details
      description: Retrieve details for the given vulnerability.
      script: '|||tenable-io-get-vulnerability-details'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      retry-count:
        simple: "2"
      vulnerabilityId:
        complex:
          root: TenableIO
          accessor: Vulnerabilities.[0].Id
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 002b1bc8-8bf1-4852-8db3-50acdbf66267
    type: regular
    task:
      id: 002b1bc8-8bf1-4852-8db3-50acdbf66267
      version: -1
      name: tenable-io-get-vulnerabilities-by-asset
      description: Get a list of up to 5000 of the vulnerabilities recorded for a
        given asset. By default, this list is sorted by vulnerability count, descending.
      script: '|||tenable-io-get-vulnerabilities-by-asset'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      hostname:
        simple: ec2-52-50-45-109.eu-west-1.compute.amazonaws.com
      retry-count:
        simple: "2"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: c1497579-2385-45af-8b68-6187baad6227
    type: regular
    task:
      id: c1497579-2385-45af-8b68-6187baad6227
      version: -1
      name: Tenable-io-export-assets
      description: Retrieves details for the specified asset to include custom attributes.
      script: '|||tenable-io-export-assets'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      chunkSize:
        simple: "500"
      serviceNowSysId:
        simple: "false"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: 4d6e868c-7d5f-4d0c-80ab-9178c72a2b8b
    type: regular
    task:
      id: 4d6e868c-7d5f-4d0c-80ab-9178c72a2b8b
      version: -1
      name: Tenable-io-export-vulnerability
      description: Retrieves details for the specified asset to include custom attributes.
      script: Tenable.io|||tenable-io-export-vulnerabilities
      type: regular
      iscommand: true
      brand: Tenable.io
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      numAssets:
        simple: "500"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: f759ff5e-828d-48c6-8d5a-332fc4527923
    type: condition
    task:
      id: f759ff5e-828d-48c6-8d5a-332fc4527923
      version: -1
      name: Verify vulnerabilities
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "13"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: TenableIO.Vulnerability.asset
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: fcc96894-3cc8-4b31-8bd3-b08aef458cde
    type: condition
    task:
      id: fcc96894-3cc8-4b31-8bd3-b08aef458cde
      version: -1
      name: Verify assets
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "8"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: TenableIO.Asset.id
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: f00cabbd-de80-45b2-890d-61c82f8dcabf
    type: title
    task:
      id: f00cabbd-de80-45b2-890d-61c82f8dcabf
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2645
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: ee1b63da-40f0-4102-86a2-cf36557f9c89
    type: regular
    task:
      id: ee1b63da-40f0-4102-86a2-cf36557f9c89
      version: -1
      name: Run get-scan-history Command
      description: Lists the individual runs of the specified scan.
      script: Tenable.io|||tenable-io-get-scan-history
      type: regular
      iscommand: true
      brand: Tenable.io
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      excludeRollover:
        simple: "true"
      limit:
        simple: "1"
      scanId:
        complex:
          root: TenableIO.Scan
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: TenableIO.Scan.Status
                iscontext: true
              right:
                value:
                  simple: completed
          accessor: Id
          transformers:
          - operator: atIndex
            args:
              index:
                value:
                  simple: "0"
      sortFields:
        simple: end_date,status
      sortOrder:
        simple: desc
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2295
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "13":
    id: "13"
    taskid: 9c7d1767-1f11-428a-8253-7105527f8083
    type: regular
    task:
      id: 9c7d1767-1f11-428a-8253-7105527f8083
      version: -1
      name: Run list-scan-filters Command
      description: Lists the filtering, sorting, and pagination capabilities available
        for scan records on endpoints/commands that support them.
      script: Tenable.io|||tenable-io-list-scan-filters
      type: regular
      iscommand: true
      brand: Tenable.io
    nexttasks:
      '#none#':
      - "15"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1945
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "14":
    id: "14"
    taskid: 0883f54e-9123-4368-835d-f6223420de1e
    type: regular
    task:
      id: 0883f54e-9123-4368-835d-f6223420de1e
      version: -1
      name: Run export-scan Command
      description: Export and download a scan report.
      script: Tenable.io|||tenable-io-export-scan
      type: regular
      iscommand: true
      brand: Tenable.io
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      chapters:
        simple: vuln_hosts_summary,remediations,compliance_exec,vuln_by_host,compliance,vuln_by_plugin
      format:
        simple: CSV
      historyId:
        simple: ${TenableIO.ScanHistory.id}
      historyUuid:
        simple: ${TenableIO.ScanHistory.scan_uuid}
      scanId:
        complex:
          root: TenableIO.Scan
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: TenableIO.Scan.Status
                iscontext: true
              right:
                value:
                  simple: completed
          accessor: Id
          transformers:
          - operator: atIndex
            args:
              index:
                value:
                  simple: "0"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2470
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "15":
    id: "15"
    taskid: fe841822-b4d5-4598-8c4d-115c7308d9be
    type: condition
    task:
      id: fe841822-b4d5-4598-8c4d-115c7308d9be
      version: -1
      name: Verify list scan filters
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "12"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: TenableIO.ScanFilter.name
            iscontext: true
      - - operator: isExists
          left:
            value:
              simple: TenableIO.ScanFilter.control.readable_regex
            iscontext: true
      - - operator: isExists
          left:
            value:
              simple: TenableIO.ScanFilter.operators
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2660,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: 5.0.0
description: ''
