id: EWS Mail Sender Test
version: -1
name: EWS Mail Sender Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 859ec50d-0674-4efd-83a6-c718dcb9cec7
    type: start
    task:
      id: 859ec50d-0674-4efd-83a6-c718dcb9cec7
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 15e5ce5e-dd47-4c97-88be-a1c8885a3a87
    type: regular
    task:
      id: 15e5ce5e-dd47-4c97-88be-a1c8885a3a87
      version: -1
      name: Test send mail
      description: Sends an email using EWS.
      script: EWS v2|||send-mail
      type: regular
      iscommand: true
      brand: EWS v2
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      attachIDs:
        simple: ${File.EntryID}
      subject:
        simple: test_rešňa
      to:
        simple: buildtests@demisto.int
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 73c00990-63d2-43da-8045-01e0ce3e01d8
    type: regular
    task:
      id: 73c00990-63d2-43da-8045-01e0ce3e01d8
      version: -1
      name: Get file
      scriptName: http
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      filename:
        simple: test_file_пожалуйста
      method:
        simple: GET
      saveAsFile:
        simple: "yes"
      url:
        simple: https://raw.githubusercontent.com/demisto/content/master/TestData/ParseEmailFiles_test_email.eml
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 80929701-a65b-4dbd-8442-e27a11422742
    type: title
    task:
      id: 80929701-a65b-4dbd-8442-e27a11422742
      version: -1
      name: Test success after failure
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: df656539-45fd-4b31-81a0-5bb95ec9bfbf
    type: regular
    task:
      id: df656539-45fd-4b31-81a0-5bb95ec9bfbf
      version: -1
      name: Send Bad Email (Should fail)
      description: Sends an email using EWS.
      script: EWS v2|||send-mail
      type: regular
      iscommand: true
      brand: EWS v2
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      attachIDs:
        simple: bad
      subject:
        simple: Bad Email That Fails
      to:
        simple: buildtests@demisto.int
    separatecontext: false
    continueonerror: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 865
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 4dda92ca-1c80-48fb-8e94-e0c1326aad6d
    type: regular
    task:
      id: 4dda92ca-1c80-48fb-8e94-e0c1326aad6d
      version: -1
      name: Send Good Email
      description: Sends an email using EWS.
      script: EWS v2|||send-mail
      type: regular
      iscommand: true
      brand: EWS v2
    scriptarguments:
      attachIDs:
        simple: ${File.EntryID}
      subject:
        simple: test
      to:
        simple: buildtests@demisto.int
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1040
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: e92a05f7-838a-42c4-84af-54a0bb4c81e7
    type: regular
    task:
      id: e92a05f7-838a-42c4-84af-54a0bb4c81e7
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1085,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: 5.0.0
