name: Check Label Workflow
on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]

permissions:
  contents: read

jobs:
  check_label_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v8
      - name: Install python dependencies
        run: |
          poetry install --with ci
      - name: set pythonpath
        run: |
          echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Check if partner-approved label exists
        id: check_label
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Checking if contribution form needs to be filled for PR: $PR_NUMBER"
          cd Utils/github_workflow_scripts
          poetry run ./check_if_partner_pack_contributed_by_others.py --pr_number $PR_NUMBER --github_token $GITHUB_TOKEN